#!/usr/bin/env bash

set -e # Exit on errors

# Check if required parameters are set
: ${BAMBOO_SERVER:?"Please use 'docker run -e BAMBOO_SERVER=...' to run this container!"}

echo "-> Starting Bamboo Agent ..."
echo "   - BAMBOO_USER:   $BAMBOO_USER"
echo "   - BAMBOO_HOME:   $BAMBOO_HOME"
echo "   - BAMBOO_SERVER: $BAMBOO_SERVER"

BAMBOO_INSTALLER=$BAMBOO_HOME/bamboo-agent-installer.jar
if [ -f $BAMBOO_INSTALLER ]; then
	echo "-> Installer already found at $BAMBOO_INSTALLER. Skipping download."
else
	BAMBOO_INSTALLER_URL=$BAMBOO_SERVER/agentServer/agentInstaller
	echo "-> Downloading installer from $BAMBOO_INSTALLER_URL ..."
	wget --progress=dot:mega $BAMBOO_INSTALLER_URL -O $BAMBOO_INSTALLER
fi

# Fix permissions
chown -R $BAMBOO_USER:$BAMBOO_USER $BAMBOO_INSTALLER

BAMBOO_AGENT=$BAMBOO_HOME/bin/bamboo-agent.sh
if [ ! -f $BAMBOO_AGENT ]; then
	echo "-> Running Bamboo Installer ..."
	su - $BAMBOO_USER -c "java -Dbamboo.home=$BAMBOO_HOME -jar $BAMBOO_INSTALLER $BAMBOO_SERVER/agentServer/ install"
fi

# Kill Bamboo process on signals from supervisor
trap '[ -f $BAMBOO_HOME/bin/bamboo-agent.pid ] && kill `cat $BAMBOO_HOME/bin/bamboo-agent.pid`' SIGINT SIGTERM EXIT

# Run the Bamboo agent
su - $BAMBOO_USER -c "$BAMBOO_AGENT console" &

# Wait for Bamboo process to terminate
wait $(jobs -p)
