#!/bin/bash

PG_VERSION=9.3

# Add Bamboo capabilities
bamboo-capability "PostgreSQL" "`pg_config --version`"
bamboo-capability-command psql

echo "=> Starting PostgreSQL $PG_VERSION ..."
su postgres -c "/usr/lib/postgresql/$PG_VERSION/bin/postgres -D /var/lib/postgresql/$PG_VERSION/main -c config_file=/etc/postgresql/$PG_VERSION/main/postgresql.conf" &

# Kill pg process on signals from supervisor
trap 'kill $(jobs -p)' SIGINT SIGTERM EXIT

# Wait for Bamboo process to terminate
wait $(jobs -p)
