#!/usr/bin/env bash 

echo "=> Current environment:"
env 

# Set timezone based on TZ env
if [ ! -z "$TZ" ]; then
  echo $TZ > /etc/timezone
  dpkg-reconfigure tzdata
fi

echo "=> Starting supervisor ..."
supervisord -c /etc/supervisor/supervisord.conf
